AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hire a friend save emails to s3

Parameters:
  Stage:
    Type: String
    Description: Name of the stage of the api-gateway
    Default: Develop
    AllowedValues:
      - Develop
      - Staging
      - Production
  S3BucketPolicy:
    Type: String
    Description: S3 policy for writing orders objects
    Default: arn:aws:iam::173088506843:policy/HireAFriendS3Policy

Globals:
  Function:
    Timeout: 3
  Api:
    OpenApiVersion: 3.0.1
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  HireAFriendSaveEmailsFunctionDevelop:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Policies: !Ref S3BucketPolicy
      Events:
        HireAFriendApiDevelop:
           Type: Api
           Properties:
            Path: /getemails
            Method: POST
            RestApiId: !Ref ApiDeploymentDevelop
      Environment:
        Variables:
          STAGE: !Ref Stage

  HireAFriendSaveEmailsFunctionStaging:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Policies: !Ref S3BucketPolicy
      Events:
        HireAFriendApiStaging:
           Type: Api
           Properties:
            Path: /getemails
            Method: POST
            RestApiId: !Ref ApiDeploymentStaging
      Environment:
        Variables:
          STAGE: !Ref Stage

  HireAFriendSaveEmailsFunctionProduction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Policies: !Ref S3BucketPolicy
      Events:
        HireAFriendApiProduction:
           Type: Api
           Properties:
            Path: /getemails
            Method: POST
            RestApiId: !Ref ApiDeploymentProduction
      Environment:
        Variables:
          STAGE: !Ref Stage
  ApiDeploymentDevelop:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
  ApiDeploymentStaging:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
  ApiDeploymentProduction:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
