AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hire a friend save emails to s3

Parameters:
  Stage:
    Type: String
    Description: Name of the stage of the api-gateway
    Default: Develop
    AllowedValues:
      - Develop
      - Staging
      - Production
  S3BucketPolicy:
    Type: String
    Description: S3 policy for writing orders objects
    Default: arn:aws:iam::173088506843:policy/HireAFriendS3Policy

Globals:
  Function:
    Timeout: 3
  Api:
    OpenApiVersion: 3.0.1
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'https://d3pc0hdqierc2c.cloudfront.net'"

Resources:
  HireAFriendSaveEmailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/lambda-save-email
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Policies: !Ref S3BucketPolicy
      Events:
        HireAFriendApi:
           Type: Api
           Properties:
            Path: /getemails
            Method: POST
            RestApiId: !Ref ApiDeployment
      Environment:
        Variables:
          STAGE: !Ref Stage
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage