orbs:
  slack: circleci/slack@4.1
version: '2.1'
executors:
  app-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.3.9

aliases:
  - &restore-cache
    restore_cache:
      keys: 
        - app-{{ checksum "./lambda-save-email/package.json" }}
        - app-
  - &install-dependencies-save-email
    run:
      name: Install dependecies
      command: |
        cd lambda-save-email
        mkdir -p artifacts
        npm install
  - &install-dependencies-sendGrid
    run:
      name: Install dependecies
      command: |
        cd lambda-sendGrid
        mkdir -p artifacts
        npm install
  - &save-cache
    save_cache:
      paths: 
        - ./node_modules/lambda-save-email
      key: app-{{ checksum "./lambda-save-email/package.json" }}
  - &install-aws-cli
    run:
      name: Installing aws cli
      working_directory: /
      command: |
        sudo apt-get -y -qq update
        sudo apt-get install -y awscli
jobs:
  deploy-to-aws-lambda:
    executor: app-executor
    steps:
      - checkout
      - *save-cache
      - *restore-cache
      - *install-dependencies-save-email
      - *install-aws-cli
      - run:
          name: Deploy to aws lambda
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
              then
                cd lambda-save-email
                export STAGE="Production"
                aws cloudformation package --template-file template.yaml --s3-bucket $AWS_BUCKET_NAME --output-template-file packaged.production.yaml
                aws cloudformation deploy --template-file packaged.production.yaml --stack-name hire-a-friend-production --capabilities CAPABILITY_IAM --s3-bucket $AWS_BUCKET_NAME --parameter-overrides Stage=Production S3BucketPolicy=$AWS_BUCKET_POLICY --region us-east-1 
                aws s3 rm s3://$AWS_BUCKET_NAME/ --exclude "emails-Develop" --exclude "emails-Production" --exclude "emails-Staging" --recursive
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
              then
                cd lambda-save-email
                export STAGE="Staging"
                aws cloudformation package --template-file template.yaml --s3-bucket $AWS_BUCKET_NAME --output-template-file packaged.staging.yaml
                aws cloudformation deploy --template-file packaged.staging.yaml --stack-name hire-a-friend-staging --capabilities CAPABILITY_IAM --s3-bucket $AWS_BUCKET_NAME --parameter-overrides Stage=Staging S3BucketPolicy=$AWS_BUCKET_POLICY --region us-east-1 
                aws s3 rm s3://$AWS_BUCKET_NAME/ --exclude "emails-Develop" --exclude "emails-Production" --exclude "emails-Staging" --recursive
            else
              cd lambda-save-email
              export STAGE="Develop"
              aws cloudformation package --template-file template.yaml --s3-bucket $AWS_BUCKET_NAME --output-template-file packaged.development.yaml
              aws cloudformation deploy --template-file packaged.development.yaml --stack-name hire-a-friend-develop --capabilities CAPABILITY_IAM --s3-bucket $AWS_BUCKET_NAME --parameter-overrides Stage=Develop S3BucketPolicy=$AWS_BUCKET_POLICY --region us-east-1 
              aws s3 rm s3://$AWS_BUCKET_NAME/ --exclude "emails-Develop" --exclude "emails-Production" --exclude "emails-Staging" --recursive
            fi
workflows:
  build_and_deploy:
    jobs:
      - deploy-to-aws-lambda