orbs:
  slack: circleci/slack@4.1
version: '2.1'
executors:
  app-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.3.9

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys: 
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependecies
      command: |
        mkdir -p artifacts
        npm install
  - &save-cache
    save_cache:
      paths: 
        - node_modules
      key: app-{{ checksum "package.json" }}
  - &install-aws-cli
    run:
      name: Installing aws cli
      working_directory: /
      command: |
        sudo apt-get -y -qq update
        sudo apt-get install -y awscli
  - &build-project
    run:
      name: Build Project
      command: |
        npm install
        zip ../build.zip -r * .[^.]*
        echo "Build successful"
jobs:
  deploy-to-aws-lambda:
    executor: app-executor
    steps:
      - checkout
      - *restore-cache
      - *install-dependencies
      - *install-aws-cli
      - run:
          name: Deploy to aws lambda
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
              then
                export STAGE="Production"
                aws cloudformation package --template-file template.yaml --s3-bucket $AWS_BUCKET_NAME --output-template-file packaged.development.yaml
                aws cloudformation deploy --template-file packaged.development.yaml --stack-name hire-a-friend --capabilities CAPABILITY_IAM --s3-bucket $AWS_BUCKET_NAME --parameter-overrides Stage=Production S3BucketPolicy=$AWS_BUCKET_POLICY --region us-east-1 
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
              then
                export STAGE="Staging"
                aws cloudformation package --template-file template.yaml --s3-bucket $AWS_BUCKET_NAME --output-template-file packaged.development.yaml
                aws cloudformation deploy --template-file packaged.development.yaml --stack-name hire-a-friend --capabilities CAPABILITY_IAM --s3-bucket $AWS_BUCKET_NAME --parameter-overrides Stage=Staging S3BucketPolicy=$AWS_BUCKET_POLICY --region us-east-1 
            else
              export STAGE="Develop"
              aws cloudformation package --template-file template.yaml --s3-bucket $AWS_BUCKET_NAME --output-template-file packaged.development.yaml
              aws cloudformation deploy --template-file packaged.development.yaml --stack-name hire-a-friend --capabilities CAPABILITY_IAM --s3-bucket $AWS_BUCKET_NAME --parameter-overrides Stage=Develop S3BucketPolicy=$AWS_BUCKET_POLICY --region us-east-1 
            fi
workflows:
  build_and_deploy:
    jobs:
      - deploy-to-aws-lambda